// automatically generated by the FlatBuffers compiler, do not modify

package com.jerolba.xbuffers.flat;

public final class OrganizationType {
  private OrganizationType() { }
  public static final byte FOO = 0;
  public static final byte BAR = 1;
  public static final byte BAZ = 2;

  public static final String[] names = { "FOO", "BAR", "BAZ", };

  public static String name(int e) { return names[e]; }
}

